FROM php:8.2-fpm-alpine

# Install system dependencies & PHP extensions yang dibutuhin Laravel
RUN alpine_version=$(cat /etc/alpine-release | cut -d'.' -f1,2) \
    && apk add --no-cache \
    nginx \
    supervisor \
    curl \
    libpng-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    oniguruma-dev \
    postgresql-dev

RUN docker-php-ext-install pdo_mysql pdo_pgsql mbstring exif pcntl bcmath xml gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy kodingan project
COPY . .

# Install dependencies Laravel production
RUN composer install --no-dev --optimize-autoloader --no-interaction

# Set up permissions buat storage Laravel bray
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Setup konfigurasi Nginx internal Docker agar mengarah ke folder public
RUN mkdir -p /run/nginx
COPY .render/nginx.conf /etc/nginx/nginx.conf
COPY .render/supervisord.conf /etc/supervisord.conf

# Jalankan optimasi cache Laravel
RUN php artisan config:cache && php artisan route:cache

EXPOSE 80

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]